"""
LLM Service - handles all LLM API interactions for question and reasoning generation.
Supports both mock responses and real GLM-4.7 API calls.
"""
from typing import List, Optional, Dict, Any
from abc import ABC, abstractmethod
import json
import httpx
from datetime import datetime
import asyncio
import structlog

from ..core.config import settings

logger = structlog.get_logger()


class LLMServiceInterface(ABC):
    """Abstract interface for LLM services."""
    
    @abstractmethod
    async def generate_question(
        self,
        category: str,
        difficulty: str = "medium",
        topic_hints: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """Generate a new MCQ question."""
        pass
    
    @abstractmethod
    async def generate_reasoning(
        self,
        question: Dict[str, Any],
        strategy: str
    ) -> Dict[str, Any]:
        """Generate reasoning for a question using specified strategy."""
        pass
    
    @abstractmethod
    async def generate_explanation(
        self,
        question: Dict[str, Any],
        correct_answer: str
    ) -> str:
        """Generate explanation for correct answer."""
        pass


class MockLLMService(LLMServiceInterface):
    """Mock LLM service for development without API access."""
    
    def __init__(self):
        self._mock_questions = self._build_mock_questions()
        self._mock_reasoning = self._build_mock_reasoning()
    
    async def generate_question(
        self,
        category: str,
        difficulty: str = "medium",
        topic_hints: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """Return a mock question based on category."""
        # Find a matching mock question or generate a generic one
        category_questions = self._mock_questions.get(category, [])
        
        if category_questions:
            import random
            return random.choice(category_questions)
        
        # Return a generic mock question
        return {
            "stem": f"A patient presents with symptoms suggestive of a {category} disorder. "
                    f"Which of the following is the most likely diagnosis?",
            "options": {
                "A": "Condition Alpha",
                "B": "Condition Beta",
                "C": "Condition Gamma",
                "D": "Condition Delta",
                "E": "Condition Epsilon"
            },
            "correct_answer": "B",
            "difficulty": difficulty,
            "category": category,
            "explanation": "This is a mock explanation for development purposes."
        }
    
    async def generate_reasoning(
        self,
        question: Dict[str, Any],
        strategy: str
    ) -> Dict[str, Any]:
        """Return mock reasoning based on strategy."""
        return self._mock_reasoning.get(strategy, self._get_default_reasoning(strategy))
    
    async def generate_explanation(
        self,
        question: Dict[str, Any],
        correct_answer: str
    ) -> str:
        """Return a mock explanation."""
        correct_option = question.get("options", {}).get(correct_answer, "Unknown")
        return (
            f"The correct answer is {correct_answer}: {correct_option}. "
            f"This is a mock explanation generated for development purposes. "
            f"In production, this would be generated by the LLM based on the "
            f"clinical presentation and underlying pathophysiology."
        )
    
    def _build_mock_questions(self) -> Dict[str, List[Dict]]:
        """Build mock questions for different categories."""
        return {
            "Lysosomal Storage Disorders": [
                {
                    "stem": "A 6-month-old infant presents with developmental regression, "
                            "exaggerated startle response, and a cherry-red spot on fundoscopic "
                            "examination. The parents are of Ashkenazi Jewish descent. "
                            "Which enzyme deficiency is most likely?",
                    "options": {
                        "A": "Glucocerebrosidase",
                        "B": "Hexosaminidase A",
                        "C": "Sphingomyelinase",
                        "D": "Alpha-galactosidase A",
                        "E": "Iduronidase"
                    },
                    "correct_answer": "B",
                    "difficulty": "medium",
                    "category": "Lysosomal Storage Disorders",
                    "explanation": "Tay-Sachs disease is caused by hexosaminidase A deficiency. "
                                   "The cherry-red spot and developmental regression are classic findings."
                }
            ],
            "Chromosomal Abnormalities": [
                {
                    "stem": "A newborn presents with hypotonia, feeding difficulties, and "
                            "low-set ears. Karyotype analysis reveals a deletion on chromosome 5. "
                            "What is the most likely diagnosis?",
                    "options": {
                        "A": "Down syndrome",
                        "B": "Edwards syndrome",
                        "C": "Cri-du-chat syndrome",
                        "D": "Prader-Willi syndrome",
                        "E": "Angelman syndrome"
                    },
                    "correct_answer": "C",
                    "difficulty": "easy",
                    "category": "Chromosomal Abnormalities",
                    "explanation": "Cri-du-chat syndrome is caused by a deletion on the short arm "
                                   "of chromosome 5 (5p-). Features include a characteristic cry, "
                                   "hypotonia, and distinctive facial features."
                }
            ]
        }
    
    def _build_mock_reasoning(self) -> Dict[str, Dict]:
        """Build mock reasoning for different strategies."""
        return {
            "association": {
                "strategy": "association",
                "steps": [
                    {
                        "step_number": 1,
                        "description": "Identify key clinical findings from the question stem",
                        "evidence": ["cherry-red spot", "developmental regression", "startle response"]
                    },
                    {
                        "step_number": 2,
                        "description": "Map findings to associated conditions",
                        "evidence": ["Tay-Sachs disease", "Niemann-Pick disease", "Sandhoff disease"]
                    },
                    {
                        "step_number": 3,
                        "description": "Use demographic information to narrow differential",
                        "evidence": ["Ashkenazi Jewish descent increases Tay-Sachs risk"]
                    }
                ],
                "conclusion": "The combination of cherry-red spot, developmental regression, "
                              "and Ashkenazi Jewish heritage strongly suggests Tay-Sachs disease.",
                "confidence": 0.95
            },
            "hypothetico": {
                "strategy": "hypothetico",
                "steps": [
                    {
                        "step_number": 1,
                        "description": "Form hypothesis: Tay-Sachs disease",
                        "supports": ["B"],
                        "opposes": []
                    },
                    {
                        "step_number": 2,
                        "description": "Test: Check for hexosaminidase A deficiency",
                        "supports": ["B"],
                        "opposes": ["A", "C", "D", "E"]
                    },
                    {
                        "step_number": 3,
                        "description": "Verify: Cherry-red spot is consistent",
                        "supports": ["B"],
                        "opposes": []
                    }
                ],
                "conclusion": "Hypothesis confirmed: Tay-Sachs disease best explains all findings.",
                "confidence": 0.92
            },
            "constraints": {
                "strategy": "constraints",
                "steps": [
                    {
                        "step_number": 1,
                        "description": "Apply constraint: Must be a lysosomal storage disorder",
                        "eliminated": []
                    },
                    {
                        "step_number": 2,
                        "description": "Apply constraint: Must cause cherry-red spot",
                        "eliminated": ["A", "D", "E"]
                    },
                    {
                        "step_number": 3,
                        "description": "Apply constraint: Must cause neurodegeneration without hepatosplenomegaly",
                        "eliminated": ["C"]
                    }
                ],
                "conclusion": "Only option B (Tay-Sachs) satisfies all constraints.",
                "confidence": 0.98
            },
            "arguments": {
                "strategy": "arguments",
                "steps": [
                    {
                        "step_number": 1,
                        "description": "Argument FOR Tay-Sachs (B)",
                        "evidence": [
                            "Cherry-red spot is characteristic",
                            "Developmental regression fits timeline",
                            "Ashkenazi Jewish heritage is risk factor"
                        ],
                        "supports": ["B"]
                    },
                    {
                        "step_number": 2,
                        "description": "Argument AGAINST Niemann-Pick (A)",
                        "evidence": [
                            "Would expect hepatosplenomegaly",
                            "Type A more severe, earlier onset"
                        ],
                        "opposes": ["A"]
                    },
                    {
                        "step_number": 3,
                        "description": "Compare strength of arguments",
                        "evidence": ["B has strongest supporting evidence"]
                    }
                ],
                "conclusion": "Argument for B is strongest and most complete.",
                "confidence": 0.90
            }
        }
    
    def _get_default_reasoning(self, strategy: str) -> Dict[str, Any]:
        """Get default reasoning structure for unknown strategies."""
        return {
            "strategy": strategy,
            "steps": [
                {
                    "step_number": 1,
                    "description": f"Mock reasoning step 1 for {strategy} strategy"
                },
                {
                    "step_number": 2,
                    "description": f"Mock reasoning step 2 for {strategy} strategy"
                }
            ],
            "conclusion": f"Mock conclusion for {strategy} reasoning strategy.",
            "confidence": 0.75
        }


class GLMService(LLMServiceInterface):
    """Real GLM-4.7 API service implementation with rate limit handling and fallback."""
    
    def __init__(self):
        self.api_url = settings.llm_api_url
        self.api_key = settings.llm_api_key
        self.model = settings.llm_model
        self.max_tokens = settings.llm_max_tokens
        self.temperature = settings.llm_temperature
        self._mock_fallback = MockLLMService()
        self._last_request_time: Optional[datetime] = None
        self._min_request_interval = 1.0  # Minimum seconds between requests
        
        if not self.api_url or not self.api_key:
            raise ValueError("LLM API URL and key must be configured")
    
    async def _wait_for_rate_limit(self):
        """Wait if necessary to comply with rate limits."""
        if self._last_request_time:
            elapsed = (datetime.now() - self._last_request_time).total_seconds()
            if elapsed < self._min_request_interval:
                wait_time = self._min_request_interval - elapsed
                logger.debug("Rate limit wait", wait_seconds=wait_time)
                await asyncio.sleep(wait_time)
        self._last_request_time = datetime.now()
    
    async def _call_api_with_retry(
        self, 
        prompt: str, 
        system_prompt: Optional[str] = None,
        max_retries: int = 3
    ) -> str:
        """Make API call with retry logic for rate limits."""
        await self._wait_for_rate_limit()
        
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})
        
        payload = {
            "model": self.model,
            "messages": messages,
            "max_tokens": self.max_tokens,
            "temperature": self.temperature
        }
        
        last_error = None
        for attempt in range(max_retries):
            try:
                async with httpx.AsyncClient() as client:
                    response = await client.post(
                        f"{self.api_url}/chat/completions",
                        headers=headers,
                        json=payload,
                        timeout=60.0
                    )
                    
                    # Handle rate limiting
                    if response.status_code == 429:
                        retry_after = float(response.headers.get("Retry-After", 5))
                        logger.warning(
                            "Rate limited, waiting",
                            retry_after=retry_after,
                            attempt=attempt + 1
                        )
                        await asyncio.sleep(retry_after)
                        continue
                    
                    response.raise_for_status()
                    data = response.json()
                    return data["choices"][0]["message"]["content"]
                    
            except httpx.HTTPStatusError as e:
                last_error = e
                logger.error(
                    "API HTTP error",
                    status_code=e.response.status_code,
                    attempt=attempt + 1,
                    error=str(e)
                )
                if e.response.status_code == 429:
                    # Rate limit - wait and retry
                    await asyncio.sleep(5 * (attempt + 1))
                    continue
                elif e.response.status_code >= 500:
                    # Server error - retry with backoff
                    await asyncio.sleep(2 ** attempt)
                    continue
                else:
                    # Client error - don't retry
                    raise
                    
            except httpx.RequestError as e:
                last_error = e
                logger.error(
                    "API request error",
                    attempt=attempt + 1,
                    error=str(e)
                )
                if attempt < max_retries - 1:
                    await asyncio.sleep(2 ** attempt)
                    continue
        
        # All retries failed
        raise Exception(f"API call failed after {max_retries} retries: {last_error}")
    
    async def _call_api(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        """Make API call to GLM-4.7 (legacy method for compatibility)."""
        return await self._call_api_with_retry(prompt, system_prompt)
    
    async def generate_question(
        self,
        category: str,
        difficulty: str = "medium",
        topic_hints: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """Generate a new MCQ question using GLM-4.7 with fallback to mock."""
        system_prompt = """You are an expert medical genetics educator creating board-style 
        multiple choice questions for medical genetics residents. Questions should be 
        clinically relevant, accurate, and follow best practices for MCQ design."""
        
        hints_text = ""
        if topic_hints:
            hints_text = f"\nFocus on these topics: {', '.join(topic_hints)}"
        
        prompt = f"""Generate a {difficulty} difficulty multiple-choice question in the 
        category of {category}.{hints_text}

        Format your response as JSON with this structure:
        {{
            "stem": "The clinical vignette/question stem",
            "options": {{
                "A": "First option",
                "B": "Second option",
                "C": "Third option",
                "D": "Fourth option",
                "E": "Fifth option"
            }},
            "correct_answer": "The letter of the correct answer",
            "explanation": "Brief explanation of why this is correct"
        }}

        Ensure the question:
        - Has a clear clinical scenario
        - Tests application of knowledge, not just recall
        - Has plausible distractors
        - Has a single best answer"""
        
        try:
            response = await self._call_api(prompt, system_prompt)
            
            try:
                # Try to parse JSON from response
                question_data = json.loads(response)
                question_data["category"] = category
                question_data["difficulty"] = difficulty
                question_data["generated_by"] = "glm-4"
                return question_data
            except json.JSONDecodeError:
                # If response isn't valid JSON, try to extract JSON from response
                import re
                json_match = re.search(r'\{[\s\S]*\}', response)
                if json_match:
                    try:
                        question_data = json.loads(json_match.group())
                        question_data["category"] = category
                        question_data["difficulty"] = difficulty
                        question_data["generated_by"] = "glm-4"
                        return question_data
                    except json.JSONDecodeError:
                        pass
                
                # Fall back to mock
                logger.warning("Failed to parse LLM response, using mock fallback")
                return await self._mock_fallback.generate_question(category, difficulty, topic_hints)
                
        except Exception as e:
            logger.warning("LLM API failed, using mock fallback", error=str(e))
            result = await self._mock_fallback.generate_question(category, difficulty, topic_hints)
            result["generated_by"] = "mock-fallback"
            return result
    
    async def generate_reasoning(
        self,
        question: Dict[str, Any],
        strategy: str
    ) -> Dict[str, Any]:
        """Generate reasoning for a question using specified strategy with fallback."""
        strategy_prompts = {
            "association": """Use association/graph-based reasoning. Identify key findings 
            and map them to associated conditions. Show how findings cluster together.""",
            
            "hypothetico": """Use hypothetico-deductive reasoning. Form a hypothesis, 
            then test it against the evidence. Show how each piece of evidence supports 
            or refutes potential diagnoses.""",
            
            "constraints": """Use constraint satisfaction reasoning. Apply constraints 
            from the clinical scenario to eliminate options. Show which options are 
            eliminated at each step and why.""",
            
            "arguments": """Use argument-based reasoning. Build arguments for and against 
            each option. Compare the strength of arguments to determine the best answer."""
        }
        
        system_prompt = f"""You are an expert medical genetics educator explaining 
        clinical reasoning. {strategy_prompts.get(strategy, '')}"""
        
        prompt = f"""Analyze this medical genetics question using {strategy} reasoning:

        Question: {question.get('stem', '')}
        
        Options:
        A: {question.get('options', {}).get('A', '')}
        B: {question.get('options', {}).get('B', '')}
        C: {question.get('options', {}).get('C', '')}
        D: {question.get('options', {}).get('D', '')}
        E: {question.get('options', {}).get('E', '')}
        
        Correct Answer: {question.get('correct_answer', '')}

        Format your response as JSON:
        {{
            "strategy": "{strategy}",
            "steps": [
                {{
                    "step_number": 1,
                    "description": "Description of this reasoning step",
                    "evidence": ["supporting evidence"],
                    "supports": ["option letters this supports"],
                    "opposes": ["option letters this opposes"]
                }}
            ],
            "conclusion": "Final conclusion",
            "confidence": 0.95
        }}"""
        
        try:
            response = await self._call_api(prompt, system_prompt)
            
            try:
                result = json.loads(response)
                result["generated_by"] = "glm-4"
                return result
            except json.JSONDecodeError:
                # Try to extract JSON from response
                import re
                json_match = re.search(r'\{[\s\S]*\}', response)
                if json_match:
                    try:
                        result = json.loads(json_match.group())
                        result["generated_by"] = "glm-4"
                        return result
                    except json.JSONDecodeError:
                        pass
                
                # Fall back to mock
                logger.warning("Failed to parse reasoning response, using mock fallback")
                result = await self._mock_fallback.generate_reasoning(question, strategy)
                result["generated_by"] = "mock-fallback"
                return result
                
        except Exception as e:
            logger.warning("LLM API failed for reasoning, using mock fallback", error=str(e))
            result = await self._mock_fallback.generate_reasoning(question, strategy)
            result["generated_by"] = "mock-fallback"
            return result
    
    async def generate_explanation(
        self,
        question: Dict[str, Any],
        correct_answer: str
    ) -> str:
        """Generate explanation for correct answer with fallback."""
        system_prompt = """You are an expert medical genetics educator providing 
        clear, educational explanations for board-style questions."""
        
        prompt = f"""Explain why the correct answer is {correct_answer} for this question:

        Question: {question.get('stem', '')}
        
        Correct Answer ({correct_answer}): {question.get('options', {}).get(correct_answer, '')}

        Provide a concise but thorough explanation that:
        1. Explains why the correct answer is right
        2. Explains the underlying pathophysiology/mechanism
        3. Mentions why other options are incorrect
        4. Includes relevant clinical pearls"""
        
        try:
            return await self._call_api(prompt, system_prompt)
        except Exception as e:
            logger.warning("LLM API failed for explanation, using mock fallback", error=str(e))
            return await self._mock_fallback.generate_explanation(question, correct_answer)


# Factory function to get the appropriate LLM service
def get_llm_service() -> LLMServiceInterface:
    """Get the appropriate LLM service based on configuration."""
    if settings.use_mock_llm or not settings.llm_api_url or not settings.llm_api_key:
        return MockLLMService()
    return GLMService()


# Singleton instance
_llm_service: Optional[LLMServiceInterface] = None


def llm_service() -> LLMServiceInterface:
    """Get or create the LLM service singleton."""
    global _llm_service
    if _llm_service is None:
        _llm_service = get_llm_service()
    return _llm_service
